// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZfRIQ5MZJJw3i2h9jEYxCtEEKzrsWiBA',
    appId: '1:560736724858:web:6f629118a2b673cc57d8c3',
    messagingSenderId: '560736724858',
    projectId: 'stayhydro-7c934',
    authDomain: 'stayhydro-7c934.firebaseapp.com',
    storageBucket: 'stayhydro-7c934.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXTCzv41ofMNmF26ioZ68cA0f7nDUNUE',
    appId: '1:560736724858:android:04505442f8c160f157d8c3',
    messagingSenderId: '560736724858',
    projectId: 'stayhydro-7c934',
    storageBucket: 'stayhydro-7c934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC771C8E-i5JL-yfF8l1aI07ZOmQLenOHs',
    appId: '1:560736724858:ios:515e7e58f85d631c57d8c3',
    messagingSenderId: '560736724858',
    projectId: 'stayhydro-7c934',
    storageBucket: 'stayhydro-7c934.firebasestorage.app',
    iosBundleId: 'com.slnova.stayhydro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC771C8E-i5JL-yfF8l1aI07ZOmQLenOHs',
    appId: '1:560736724858:ios:515e7e58f85d631c57d8c3',
    messagingSenderId: '560736724858',
    projectId: 'stayhydro-7c934',
    storageBucket: 'stayhydro-7c934.firebasestorage.app',
    iosBundleId: 'com.slnova.stayhydro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZfRIQ5MZJJw3i2h9jEYxCtEEKzrsWiBA',
    appId: '1:560736724858:web:9ca91e3ead2fd18757d8c3',
    messagingSenderId: '560736724858',
    projectId: 'stayhydro-7c934',
    authDomain: 'stayhydro-7c934.firebaseapp.com',
    storageBucket: 'stayhydro-7c934.firebasestorage.app',
  );
}
